version: '3'
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: amasuapp-postgresql
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-local
    restart: always
    environment:
      ORACLE_PWD: Ora1234
    ports:
      - "1521:1521"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge