version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-local
    restart: always
    environment:
      ORACLE_PWD: Ora1234
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  oracle-data: