spring:
  application:
    name: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"
  datasource:
    url:
    username:
    password:
    driver-class-name:
  profiles:
    active: dev