spring:
  application:
    name: "@project.artifactId@"
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:free
    username: system
    password: Ora1234
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        use_sql_comments: true
    open-in-view: true
    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
server:
  port: 8090
